Page({
  data:{
    phone_numbers: [
      {
        id:"num-1",
        organization:"公安报警",
        num:"110"
      },{
        id:"num-2",
        organization:"火警",
        num:"119"
      },{
        id:"num-3",
        organization:"救护",
        num:"120"
      },{
        id:"num-4",
        organization:"燃气热线",
        num:"962777"
      },{
        id:"num-5",
        organization:"物业管理处电话",
        num:"87855211"
      },{
        id:"num-6",
        organization:"滨文社区",
        num:"88071861"
      },{
        id:"num-7",
        organization:"高教园区派出所",
        num:"87697070"
      }]
  },
  call:function(e){
    var phone_num = e.target.dataset.phoneNum;
    wx.makePhoneCall({
      phoneNumber: phone_num
    })
  }
})
